version: "3"

services:
  # Service Backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    networks:
      - liaison

  # Service Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - liaison

networks:
  liaison:
    driver: bridge

volumes:
  mongodb_data:
